### PR TITLE
To fix duckduckgo_search compatibility issues 

### PR DESCRIPTION
**Pull request by tom5610**
Using class DDGS rather than calling ddg functions directly.

### CODE REVIEW

**Review by GitExcited — APPROVED** [review]
This is perfect! It fixes it for me

**Comment by Fernandes2692** [comment]
THANK YOU!

**Review by PranithChowdary — APPROVED** [review]

**Comment by PranithChowdary** [comment]
@tom5610 the code is perfect bro. you can even enhance it as below so the learner can understand it easily

```
from duckduckgo_search import DDGS
from fastcore.all import *

def search_images(term, max_images): 
    return L(DDGS().images(keywords=term, max_results=max_images)).itemgot('image')
```

```
urls = search_images("birds",100)
urls[0]
```

**Comment by wardu** [comment]
I just came here to make this exact pull request! Fix works

**Comment by jph00** [comment]
I think #108 makes this redundant.

**Pull request closed without merging**
