### PR TITLE
Updated the DuckDuckGo import and getting images function

### PR DESCRIPTION
**Pull request by MMurtazanb**
This is a minor change and one can search for a solution and get it, but the premise that anyone can actually open the notebook, run it and see instant results is so cool. With this change in the ddg api there is an error which needs to be corrected before you can complete the run.

### CODE REVIEW

**Comment by anrikus** [comment]
The current PR has the outputs included. I would suggest revising the PR with the outputs cleared.

**Comment by MMurtazanb** [comment]
@anrikus - Updated the file and the clean version and resubmitted the PR. Please help to check and merge if all good.
Thanks

**Comment by tonybustamante** [comment]
I'm relatively new to code review with regards to jupyter notebooks, but it looks like there is also quite a bit of noise included in the pull request that pertains the the jupyter notebook environment.

**Comment by jph00** [comment]
Many thanks!

**Pull request merged**
